name: el_moshwar
description: "Egyptian Cost & Route Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_map: ^6.0.0
  geolocator: ^10.1.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.2.1
  intl: ^0.19.0
  latlong2: ^0.9.0
  lottie: ^3.3.2
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  random_avatar: ^0.0.8
  supabase_flutter: ^2.0.0
  location: ^5.0.3
  url_launcher: ^6.2.1
  geocoding: ^4.0.0
  cached_network_image: ^3.4.1
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  app_links: ^6.3.0
  gal: ^2.3.2
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0+3
  timezone: ^0.10.1
  font_awesome_flutter: ^10.12.0
  timeago: ^3.7.1
  uuid: ^4.2.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  # Code Generation
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/egypt_cars.json
    - assets/animations/
    - assets/logo/
